### ISSUE TITLE
Consider keeping comments with posts

### ISSUE THREAD

**Issue by brookeangel** [momajd/InsanFran#1]
Since comments are associated with a post, consider keeping everything in the PostStore and simply creating a jbuilder template that sends back the post as well as its associated comments when you go to PostDetail. This may make it easier to keep your components in sync. Find me and chat about this if you have any questions about this and I'd be happy to explain the reasoning.

**Comment by momajd** [comment]
Sounds good, everything will be in PostStore. Later on, I may add a LikeStore so that users that liked a post can be displayed
