### ISSUE TITLE
Clarify likes

### ISSUE THREAD

**Issue by brookeangel** [momajd/InsanFran#2]
How will likes be stored? Will there be a special LikeStore or will they be stored alongside their associated posts?

**Comment by brookeangel** [comment]
Oops, just read on a little bit and saw that you do plan to keep a LikeStore. 👍  Will you be storing like objects in the LikeStore, or just a count of likes?

**Comment by momajd** [comment]
Hi Brooke,

Thanks for reviewing my proposal. To answer your question regarding likes,
I was planning on just displaying a total number of likes on each post, so
I didn't think a like store would be necessary. Please let me know if you
think I should take another approach.

I look forward to working with you!

-Mo

**Comment by brookeangel** [comment]
Sounds great!
