### ISSUE TITLE
Work in time for positioning before phase 7

### ISSUE THREAD

**Issue by brookeangel** [momajd/InsanFran#5]
It takes longer than you think to style things. Save all of  your real styling for phase 7, but make sure to get things positioned in the right place before then.

**Comment by brookeangel** [comment]
Also, I'd save infinite scroll for a bonus feature and work on the main styling first - styling is a major time sink but is super important

**Comment by momajd** [comment]
Sounds good. I removed styling from all phases except that last one. I also removed the Infinite Scroll and added it as a bonus feature.
